
import java.awt.Color;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author marti
 */
public class TicTacToe extends javax.swing.JFrame {

    private char currentPlayer;
    private boolean winnerFound = false;
    private int playerXScore = 0;
    private int playerOScore = 0;
    private boolean isFirst = true;
    private final char playerX = 'X';
    private final char playerO = 'O';
    private final Color playerXcolor = Color.red;
    private final Color playerOcolor = Color.blue;

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();

        firstMove();

    }

    /**
     * This method determines which player will start the game and updates the
     * display accordingly. If the game is restarted, the starting player
     * alternates.
     */
    private void firstMove() {

        if (isFirst) {
            currentPlayer = playerX;
            lblDisplay.setText("O turn");
            lblDisplay.setForeground(playerOcolor);

            isFirst = false;
        } else {
            currentPlayer = playerO;
            lblDisplay.setText("X turn");
            lblDisplay.setForeground(playerXcolor);
            isFirst = true;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        lblDisplay = new javax.swing.JLabel();
        lblScoreX = new javax.swing.JLabel();
        lblScoreO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIC-TAC-TOE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn2.setFocusable(false);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 100));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn3.setFocusable(false);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 100, 100));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn4.setFocusable(false);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn4MousePressed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 100));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn7.setFocusable(false);
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn7MousePressed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 100));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn5.setFocusable(false);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn5MousePressed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, 100));

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn8.setFocusable(false);
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn8MousePressed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 100, 100));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn6.setFocusable(false);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn6MousePressed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 100));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn9.setFocusable(false);
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn9MousePressed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 100, 100));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn1.setFocusable(false);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 100));

        btnReset.setBackground(new java.awt.Color(255, 255, 102));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("RESET");
        btnReset.setFocusable(false);
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResetMousePressed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 150, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Player X");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 75, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Player O");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 75, 50));

        btnClear.setBackground(new java.awt.Color(102, 255, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("CLEAR SCORE");
        btnClear.setFocusable(false);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClearMousePressed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 300, 50));

        lblDisplay.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        lblScoreX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblScoreX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreX.setText("0");
        lblScoreX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblScoreX, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 360, 75, 50));

        lblScoreO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblScoreO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreO.setText("0");
        lblScoreO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblScoreO, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 410, 75, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Switches the current player between X and O after each move and updates
     * the display to reflect whose turn it is next. If the current player is X,
     * it switches to O, and vice versa.
     *
     * @param button The button representing the cell where the player made a
     * move.
     */
    private void switchPlayer(JButton button) {

        if (currentPlayer == playerO) {
            currentPlayer = playerX;
            button.setText(String.valueOf(playerX));
            button.setForeground(playerXcolor);
            lblDisplay.setText("O turn");
            lblDisplay.setForeground(playerOcolor);

        } else {
            currentPlayer = playerO;
            button.setText(String.valueOf(playerO));
            button.setForeground(playerOcolor);
            lblDisplay.setText("X turn");
            lblDisplay.setForeground(playerXcolor);

        }
    }

    /**
     * Checks for a winning condition or a tie in the Tic Tac Toe game. Updates
     * the scores, highlights winning cells, and displays the result.
     */
    private void winner() {

        boolean tie = true;

        //all possibly winner combinations
        JButton[][] select = {
            {btn1, btn2, btn3},
            {btn4, btn5, btn6},
            {btn7, btn8, btn9},
            {btn1, btn4, btn7},
            {btn2, btn5, btn8},
            {btn3, btn6, btn9},
            {btn1, btn5, btn9},
            {btn3, btn5, btn7}
        };

        for (JButton[] jButtons : select) {
            //calling checkAll method
            if (checkAll(jButtons, String.valueOf(playerX))) {
                playerXScore++;
                lblScoreX.setText(String.valueOf(playerXScore));

                for (JButton eachButton : jButtons) {

                    eachButton.setBackground(Color.green);
                    lblDisplay.setText("X WINNER");
                    lblDisplay.setForeground(playerXcolor);
                    winnerFound = true;

                }
                //calling checkAll method
            } else if (checkAll(jButtons, String.valueOf(playerO))) {
                playerOScore++;
                lblScoreO.setText(String.valueOf(playerOScore));

                for (JButton eachButton : jButtons) {

                    eachButton.setBackground(Color.green);
                    lblDisplay.setText("O WINNER");
                    lblDisplay.setForeground(playerOcolor);
                    winnerFound = true;

                }

            } else {
                for (JButton eachButton : jButtons) {
                    if (eachButton.getText().isEmpty()) {
                        tie = false;
                    }
                }
            }

        }

        if (tie && !winnerFound) {

            lblDisplay.setText("TIE");
            lblDisplay.setForeground(Color.DARK_GRAY);

        }
    }

    /**
     * Checks if all buttons in a row, column, or diagonal have the same text
     * value.
     *
     * @param button An array of buttons representing a row, column, or
     * diagonal.
     * @param text The text value to compare against.
     * @return True if all buttons have the same text value, false otherwise.
     */
    private boolean checkAll(JButton[] button, String text) {

        for (JButton jButton : button) {
            if (!jButton.getText().equals(text)) {
                return false;

            }

        }

        return true;
    }

    //clear all buttons
    private void clear() {
        winnerFound = false; //Reset the flag for winner status
        JButton[] buttons = {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9};
        for (JButton button : buttons) {
            button.setText("");
            button.setBackground(null);

        }
//Determine starting player for the new game
        firstMove();
    }

    /**
     * Handles mouse click events on Tic Tac Toe buttons.
     *
     * Retrieves the button clicked and checks if it's empty and no winner has
     * been found. If conditions are met, switches the player and checks for a
     * winner.
     *
     * @param evt The MouseEvent representing the mouse click event.
     */
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {
        JButton jButton = (JButton) evt.getSource();
        if (!winnerFound && jButton.getText().isEmpty()) {
            switchPlayer(jButton);
            winner();

        }
    }


    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
        buttonMousePressed(evt);
    }//GEN-LAST:event_btn1MousePressed

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn2MousePressed


    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn3MousePressed

    private void btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn4MousePressed

    private void btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn5MousePressed

    private void btn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn6MousePressed

    private void btn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn7MousePressed

    private void btn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn8MousePressed

    private void btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MousePressed
        buttonMousePressed(evt);
            }//GEN-LAST:event_btn9MousePressed

    private void btnResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMousePressed
        clear();
    }//GEN-LAST:event_btnResetMousePressed

    // Clears the scores for both players.
    private void btnClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMousePressed
        playerOScore = 0;
        playerXScore = 0;
        lblScoreO.setText(String.valueOf(0));
        lblScoreX.setText(String.valueOf(0));
    }//GEN-LAST:event_btnClearMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TicTacToe().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblScoreO;
    private javax.swing.JLabel lblScoreX;
    // End of variables declaration//GEN-END:variables
}
